deployments:
  tamatem-technical-assignment:
    containers:
      tamatem-technical-assignment:
        image: "basharkhouri610/tamatem-technical-assignment:arm64" # Replace with your image or you can use this one tags available: (latest, amd64)or arm64
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "128m"
        containerPorts:
          - name: http
            containerPort: 8080
            protocol: TCP
        extraVars:
          PORT: '8080'
        readinessProbe:
          initialDelaySeconds:   5
          periodSeconds: 20
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /
            port: http
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: /
            port: http
    replicaCount: 1
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 10%

services:
  tamatem-technical-assignment:
   type: NodePort
   ports:
      - name: http
        port: 8080
        targetPort: http
        nodePort: 30001

hpas:
  tamatem-technical-assignment:
    enabled: true
    targetCPUUtilizationPercentage: 50
    minReplicas: 1
    maxReplicas: 3
